//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Program", Namespace="http://schemas.datacontract.org/2004/07/CatWorkbookPrismPoc.Services.Contracts.Da" +
        "ta")]
    [System.SerializableAttribute()]
    public partial class Program : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AuthorizedExpiringStructureIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorizedStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoundStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ExpiringProgramIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MasterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgramIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuoteExpiringStructureIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuoteStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuoteStructureIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnderwriterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnderwriterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AuthorizedExpiringStructureID {
            get {
                return this.AuthorizedExpiringStructureIDField;
            }
            set {
                if ((this.AuthorizedExpiringStructureIDField.Equals(value) != true)) {
                    this.AuthorizedExpiringStructureIDField = value;
                    this.RaisePropertyChanged("AuthorizedExpiringStructureID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorizedStatus {
            get {
                return this.AuthorizedStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorizedStatusField, value) != true)) {
                    this.AuthorizedStatusField = value;
                    this.RaisePropertyChanged("AuthorizedStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BoundStatus {
            get {
                return this.BoundStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BoundStatusField, value) != true)) {
                    this.BoundStatusField = value;
                    this.RaisePropertyChanged("BoundStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EffectiveDate {
            get {
                return this.EffectiveDateField;
            }
            set {
                if ((this.EffectiveDateField.Equals(value) != true)) {
                    this.EffectiveDateField = value;
                    this.RaisePropertyChanged("EffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExpiringProgramID {
            get {
                return this.ExpiringProgramIDField;
            }
            set {
                if ((this.ExpiringProgramIDField.Equals(value) != true)) {
                    this.ExpiringProgramIDField = value;
                    this.RaisePropertyChanged("ExpiringProgramID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasterNumber {
            get {
                return this.MasterNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MasterNumberField, value) != true)) {
                    this.MasterNumberField = value;
                    this.RaisePropertyChanged("MasterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.ModifiedOnField;
            }
            set {
                if ((this.ModifiedOnField.Equals(value) != true)) {
                    this.ModifiedOnField = value;
                    this.RaisePropertyChanged("ModifiedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgramID {
            get {
                return this.ProgramIDField;
            }
            set {
                if ((this.ProgramIDField.Equals(value) != true)) {
                    this.ProgramIDField = value;
                    this.RaisePropertyChanged("ProgramID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramName {
            get {
                return this.ProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramNameField, value) != true)) {
                    this.ProgramNameField = value;
                    this.RaisePropertyChanged("ProgramName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuoteExpiringStructureID {
            get {
                return this.QuoteExpiringStructureIDField;
            }
            set {
                if ((this.QuoteExpiringStructureIDField.Equals(value) != true)) {
                    this.QuoteExpiringStructureIDField = value;
                    this.RaisePropertyChanged("QuoteExpiringStructureID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuoteStatus {
            get {
                return this.QuoteStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.QuoteStatusField, value) != true)) {
                    this.QuoteStatusField = value;
                    this.RaisePropertyChanged("QuoteStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuoteStructureID {
            get {
                return this.QuoteStructureIDField;
            }
            set {
                if ((this.QuoteStructureIDField.Equals(value) != true)) {
                    this.QuoteStructureIDField = value;
                    this.RaisePropertyChanged("QuoteStructureID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamID {
            get {
                return this.TeamIDField;
            }
            set {
                if ((this.TeamIDField.Equals(value) != true)) {
                    this.TeamIDField = value;
                    this.RaisePropertyChanged("TeamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName {
            get {
                return this.TeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamNameField, value) != true)) {
                    this.TeamNameField = value;
                    this.RaisePropertyChanged("TeamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnderwriterID {
            get {
                return this.UnderwriterIDField;
            }
            set {
                if ((this.UnderwriterIDField.Equals(value) != true)) {
                    this.UnderwriterIDField = value;
                    this.RaisePropertyChanged("UnderwriterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnderwriterName {
            get {
                return this.UnderwriterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UnderwriterNameField, value) != true)) {
                    this.UnderwriterNameField = value;
                    this.RaisePropertyChanged("UnderwriterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/CatWorkbookPrismPoc.Services.Contracts.Fa" +
        "ults")]
    [System.SerializableAttribute()]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCriticalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCritical {
            get {
                return this.IsCriticalField;
            }
            set {
                if ((this.IsCriticalField.Equals(value) != true)) {
                    this.IsCriticalField = value;
                    this.RaisePropertyChanged("IsCritical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatWorkbookPrisimPoc.Business.ICatWorkbookService")]
    public interface ICatWorkbookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatWorkbookService/GetProgramById", ReplyAction="http://tempuri.org/ICatWorkbookService/GetProgramByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.ServiceException), Action="http://tempuri.org/ICatWorkbookService/GetProgramByIdServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/CatWorkbookPrismPoc.Services.Contracts.Fa" +
            "ults")]
        CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.Program GetProgramById(int programId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatWorkbookService/GetProgramById", ReplyAction="http://tempuri.org/ICatWorkbookService/GetProgramByIdResponse")]
        System.Threading.Tasks.Task<CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.Program> GetProgramByIdAsync(int programId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatWorkbookService/GetUnderwriters", ReplyAction="http://tempuri.org/ICatWorkbookService/GetUnderwritersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.ServiceException), Action="http://tempuri.org/ICatWorkbookService/GetUnderwritersServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/CatWorkbookPrismPoc.Services.Contracts.Fa" +
            "ults")]
        System.Collections.Generic.Dictionary<int, string> GetUnderwriters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatWorkbookService/GetUnderwriters", ReplyAction="http://tempuri.org/ICatWorkbookService/GetUnderwritersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> GetUnderwritersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatWorkbookService/GetEffectiveYears", ReplyAction="http://tempuri.org/ICatWorkbookService/GetEffectiveYearsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.ServiceException), Action="http://tempuri.org/ICatWorkbookService/GetEffectiveYearsServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/CatWorkbookPrismPoc.Services.Contracts.Fa" +
            "ults")]
        int[] GetEffectiveYears();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatWorkbookService/GetEffectiveYears", ReplyAction="http://tempuri.org/ICatWorkbookService/GetEffectiveYearsResponse")]
        System.Threading.Tasks.Task<int[]> GetEffectiveYearsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatWorkbookService/GetPrograms", ReplyAction="http://tempuri.org/ICatWorkbookService/GetProgramsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.ServiceException), Action="http://tempuri.org/ICatWorkbookService/GetProgramsServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/CatWorkbookPrismPoc.Services.Contracts.Fa" +
            "ults")]
        CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.Program[] GetPrograms(int underwriterId, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatWorkbookService/GetPrograms", ReplyAction="http://tempuri.org/ICatWorkbookService/GetProgramsResponse")]
        System.Threading.Tasks.Task<CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.Program[]> GetProgramsAsync(int underwriterId, int year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatWorkbookServiceChannel : CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.ICatWorkbookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatWorkbookServiceClient : System.ServiceModel.ClientBase<CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.ICatWorkbookService>, CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.ICatWorkbookService {
        
        public CatWorkbookServiceClient() {
        }
        
        public CatWorkbookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatWorkbookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatWorkbookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatWorkbookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.Program GetProgramById(int programId) {
            return base.Channel.GetProgramById(programId);
        }
        
        public System.Threading.Tasks.Task<CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.Program> GetProgramByIdAsync(int programId) {
            return base.Channel.GetProgramByIdAsync(programId);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetUnderwriters() {
            return base.Channel.GetUnderwriters();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> GetUnderwritersAsync() {
            return base.Channel.GetUnderwritersAsync();
        }
        
        public int[] GetEffectiveYears() {
            return base.Channel.GetEffectiveYears();
        }
        
        public System.Threading.Tasks.Task<int[]> GetEffectiveYearsAsync() {
            return base.Channel.GetEffectiveYearsAsync();
        }
        
        public CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.Program[] GetPrograms(int underwriterId, int year) {
            return base.Channel.GetPrograms(underwriterId, year);
        }
        
        public System.Threading.Tasks.Task<CatWorkbookPrismPoc.Business.CatWorkbookPrisimPoc.Business.Program[]> GetProgramsAsync(int underwriterId, int year) {
            return base.Channel.GetProgramsAsync(underwriterId, year);
        }
    }
}
